#!/usr/bin/env python
import sys
import subprocess

class Unbuffered(object):
   def __init__(self, stream):
       self.stream = stream
   def write(self, data):
       self.stream.write(data)
       self.stream.flush()
   def writelines(self, datas):
       self.stream.writelines(datas)
       self.stream.flush()
   def __getattr__(self, attr):
       return getattr(self.stream, attr)

sys.stdout = Unbuffered(sys.stdout)

try:
	while True:
		cmd = raw_input('> ')
		if cmd == 'exit':
			break
		p = subprocess.Popen(cmd, bufsize=0, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
		p.wait()
		print p.returncode
except Exception:
	exit()
except KeyboardInterrupt:
	exit()

